- name: Deploy Portainer Agent
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:latest
    restart_policy: always
    ports:
      - "9001:9001"
    env:
      AGENT_SECRET: "{{ agent_secret }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
