---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Display available upgrades
  shell: apt list --upgradable 2>/dev/null | grep -v "WARNING" | wc -l
  register: upgradable_count
  changed_when: false

- name: Show number of available upgrades
  debug:
    msg: "Доступно обновлений: {{ upgradable_count.stdout | int - 1 }}"

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  register: upgrade_result

- name: Display upgrade results
  debug:
    msg: |
      Обновление пакетов завершено!
      Изменено: {{ upgrade_result.changed }}
      {% if upgrade_result.changed %}
      Обновленные пакеты: {{ upgrade_result.stdout_lines | length }}
      {% endif %}

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Display reboot status
  debug:
    msg: "{% if reboot_required.stat.exists %}Требуется перезагрузка сервера!{% else %}Перезагрузка не требуется{% endif %}"

- name: Remove unused packages
  apt:
    autoremove: yes
    purge: yes

- name: Clean package cache
  apt:
    autoclean: yes

- name: Update package database
  apt:
    update_cache: yes
  when: upgrade_result.changed

- name: Show disk space after cleanup
  shell: df -h / | tail -1 | awk '{print $4}'
  register: disk_space
  changed_when: false

- name: Display available disk space
  debug:
    msg: "Свободное место на диске: {{ disk_space.stdout }}"
